// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type ProductType int32

const (
	ProductType_PRODUCT_TYPE_UNSPECIFIED ProductType = 0
	ProductType_digital                  ProductType = 1
	ProductType_physical                 ProductType = 2
	ProductType_subscription             ProductType = 3
)

// Enum value maps for ProductType.
var (
	ProductType_name = map[int32]string{
		0: "PRODUCT_TYPE_UNSPECIFIED",
		1: "digital",
		2: "physical",
		3: "subscription",
	}
	ProductType_value = map[string]int32{
		"PRODUCT_TYPE_UNSPECIFIED": 0,
		"digital":                  1,
		"physical":                 2,
		"subscription":             3,
	}
)

func (x ProductType) Enum() *ProductType {
	p := new(ProductType)
	*p = x
	return p
}

func (x ProductType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_product_proto_enumTypes[0].Descriptor()
}

func (ProductType) Type() protoreflect.EnumType {
	return &file_api_proto_product_proto_enumTypes[0]
}

func (x ProductType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductType.Descriptor instead.
func (ProductType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{0}
}

// Type-specific details
type DigitalProductDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileSize      int64                  `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	DownloadLink  string                 `protobuf:"bytes,2,opt,name=download_link,json=downloadLink,proto3" json:"download_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalProductDetails) Reset() {
	*x = DigitalProductDetails{}
	mi := &file_api_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalProductDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalProductDetails) ProtoMessage() {}

func (x *DigitalProductDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalProductDetails.ProtoReflect.Descriptor instead.
func (*DigitalProductDetails) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *DigitalProductDetails) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *DigitalProductDetails) GetDownloadLink() string {
	if x != nil {
		return x.DownloadLink
	}
	return ""
}

type PhysicalProductDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float64                `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Dimensions    string                 `protobuf:"bytes,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalProductDetails) Reset() {
	*x = PhysicalProductDetails{}
	mi := &file_api_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalProductDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalProductDetails) ProtoMessage() {}

func (x *PhysicalProductDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalProductDetails.ProtoReflect.Descriptor instead.
func (*PhysicalProductDetails) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *PhysicalProductDetails) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PhysicalProductDetails) GetDimensions() string {
	if x != nil {
		return x.Dimensions
	}
	return ""
}

type SubscriptionProductDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionPeriod string                 `protobuf:"bytes,1,opt,name=subscription_period,json=subscriptionPeriod,proto3" json:"subscription_period,omitempty"`
	RenewalPrice       float64                `protobuf:"fixed64,2,opt,name=renewal_price,json=renewalPrice,proto3" json:"renewal_price,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubscriptionProductDetails) Reset() {
	*x = SubscriptionProductDetails{}
	mi := &file_api_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionProductDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionProductDetails) ProtoMessage() {}

func (x *SubscriptionProductDetails) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionProductDetails.ProtoReflect.Descriptor instead.
func (*SubscriptionProductDetails) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionProductDetails) GetSubscriptionPeriod() string {
	if x != nil {
		return x.SubscriptionPeriod
	}
	return ""
}

func (x *SubscriptionProductDetails) GetRenewalPrice() float64 {
	if x != nil {
		return x.RenewalPrice
	}
	return 0
}

// Common Product Message
type Product struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Type        ProductType            `protobuf:"varint,5,opt,name=type,proto3,enum=product.ProductType" json:"type,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Types that are valid to be assigned to ProductDetails:
	//
	//	*Product_DigitalDetails
	//	*Product_PhysicalDetails
	//	*Product_SubscriptionDetails
	ProductDetails isProduct_ProductDetails `protobuf_oneof:"product_details"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetType() ProductType {
	if x != nil {
		return x.Type
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetProductDetails() isProduct_ProductDetails {
	if x != nil {
		return x.ProductDetails
	}
	return nil
}

func (x *Product) GetDigitalDetails() *DigitalProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*Product_DigitalDetails); ok {
			return x.DigitalDetails
		}
	}
	return nil
}

func (x *Product) GetPhysicalDetails() *PhysicalProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*Product_PhysicalDetails); ok {
			return x.PhysicalDetails
		}
	}
	return nil
}

func (x *Product) GetSubscriptionDetails() *SubscriptionProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*Product_SubscriptionDetails); ok {
			return x.SubscriptionDetails
		}
	}
	return nil
}

type isProduct_ProductDetails interface {
	isProduct_ProductDetails()
}

type Product_DigitalDetails struct {
	DigitalDetails *DigitalProductDetails `protobuf:"bytes,8,opt,name=digital_details,json=digitalDetails,proto3,oneof"`
}

type Product_PhysicalDetails struct {
	PhysicalDetails *PhysicalProductDetails `protobuf:"bytes,9,opt,name=physical_details,json=physicalDetails,proto3,oneof"`
}

type Product_SubscriptionDetails struct {
	SubscriptionDetails *SubscriptionProductDetails `protobuf:"bytes,10,opt,name=subscription_details,json=subscriptionDetails,proto3,oneof"`
}

func (*Product_DigitalDetails) isProduct_ProductDetails() {}

func (*Product_PhysicalDetails) isProduct_ProductDetails() {}

func (*Product_SubscriptionDetails) isProduct_ProductDetails() {}

// Requests and Responses
type CreateProductRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Type        ProductType            `protobuf:"varint,4,opt,name=type,proto3,enum=product.ProductType" json:"type,omitempty"`
	// Types that are valid to be assigned to ProductDetails:
	//
	//	*CreateProductRequest_DigitalDetails
	//	*CreateProductRequest_PhysicalDetails
	//	*CreateProductRequest_SubscriptionDetails
	ProductDetails isCreateProductRequest_ProductDetails `protobuf_oneof:"product_details"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_api_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetType() ProductType {
	if x != nil {
		return x.Type
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (x *CreateProductRequest) GetProductDetails() isCreateProductRequest_ProductDetails {
	if x != nil {
		return x.ProductDetails
	}
	return nil
}

func (x *CreateProductRequest) GetDigitalDetails() *DigitalProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*CreateProductRequest_DigitalDetails); ok {
			return x.DigitalDetails
		}
	}
	return nil
}

func (x *CreateProductRequest) GetPhysicalDetails() *PhysicalProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*CreateProductRequest_PhysicalDetails); ok {
			return x.PhysicalDetails
		}
	}
	return nil
}

func (x *CreateProductRequest) GetSubscriptionDetails() *SubscriptionProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*CreateProductRequest_SubscriptionDetails); ok {
			return x.SubscriptionDetails
		}
	}
	return nil
}

type isCreateProductRequest_ProductDetails interface {
	isCreateProductRequest_ProductDetails()
}

type CreateProductRequest_DigitalDetails struct {
	DigitalDetails *DigitalProductDetails `protobuf:"bytes,5,opt,name=digital_details,json=digitalDetails,proto3,oneof"`
}

type CreateProductRequest_PhysicalDetails struct {
	PhysicalDetails *PhysicalProductDetails `protobuf:"bytes,6,opt,name=physical_details,json=physicalDetails,proto3,oneof"`
}

type CreateProductRequest_SubscriptionDetails struct {
	SubscriptionDetails *SubscriptionProductDetails `protobuf:"bytes,7,opt,name=subscription_details,json=subscriptionDetails,proto3,oneof"`
}

func (*CreateProductRequest_DigitalDetails) isCreateProductRequest_ProductDetails() {}

func (*CreateProductRequest_PhysicalDetails) isCreateProductRequest_ProductDetails() {}

func (*CreateProductRequest_SubscriptionDetails) isCreateProductRequest_ProductDetails() {}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateProductRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	// Types that are valid to be assigned to ProductDetails:
	//
	//	*UpdateProductRequest_DigitalDetails
	//	*UpdateProductRequest_PhysicalDetails
	//	*UpdateProductRequest_SubscriptionDetails
	ProductDetails isUpdateProductRequest_ProductDetails `protobuf_oneof:"product_details"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_api_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetProductDetails() isUpdateProductRequest_ProductDetails {
	if x != nil {
		return x.ProductDetails
	}
	return nil
}

func (x *UpdateProductRequest) GetDigitalDetails() *DigitalProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*UpdateProductRequest_DigitalDetails); ok {
			return x.DigitalDetails
		}
	}
	return nil
}

func (x *UpdateProductRequest) GetPhysicalDetails() *PhysicalProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*UpdateProductRequest_PhysicalDetails); ok {
			return x.PhysicalDetails
		}
	}
	return nil
}

func (x *UpdateProductRequest) GetSubscriptionDetails() *SubscriptionProductDetails {
	if x != nil {
		if x, ok := x.ProductDetails.(*UpdateProductRequest_SubscriptionDetails); ok {
			return x.SubscriptionDetails
		}
	}
	return nil
}

type isUpdateProductRequest_ProductDetails interface {
	isUpdateProductRequest_ProductDetails()
}

type UpdateProductRequest_DigitalDetails struct {
	DigitalDetails *DigitalProductDetails `protobuf:"bytes,5,opt,name=digital_details,json=digitalDetails,proto3,oneof"`
}

type UpdateProductRequest_PhysicalDetails struct {
	PhysicalDetails *PhysicalProductDetails `protobuf:"bytes,6,opt,name=physical_details,json=physicalDetails,proto3,oneof"`
}

type UpdateProductRequest_SubscriptionDetails struct {
	SubscriptionDetails *SubscriptionProductDetails `protobuf:"bytes,7,opt,name=subscription_details,json=subscriptionDetails,proto3,oneof"`
}

func (*UpdateProductRequest_DigitalDetails) isUpdateProductRequest_ProductDetails() {}

func (*UpdateProductRequest_PhysicalDetails) isUpdateProductRequest_ProductDetails() {}

func (*UpdateProductRequest_SubscriptionDetails) isUpdateProductRequest_ProductDetails() {}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_api_proto_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TypeFilter    ProductType            `protobuf:"varint,3,opt,name=type_filter,json=typeFilter,proto3,enum=product.ProductType" json:"type_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_api_proto_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetTypeFilter() ProductType {
	if x != nil {
		return x.TypeFilter
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_api_proto_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{9}
}

func (x *ProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_api_proto_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_product_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_api_proto_product_proto protoreflect.FileDescriptor

const file_api_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/product.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\x15DigitalProductDetails\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x03R\bfileSize\x12#\n" +
	"\rdownload_link\x18\x02 \x01(\tR\fdownloadLink\"P\n" +
	"\x16PhysicalProductDetails\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x01R\x06weight\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x01(\tR\n" +
	"dimensions\"r\n" +
	"\x1aSubscriptionProductDetails\x12/\n" +
	"\x13subscription_period\x18\x01 \x01(\tR\x12subscriptionPeriod\x12#\n" +
	"\rrenewal_price\x18\x02 \x01(\x01R\frenewalPrice\"\x8b\x04\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12(\n" +
	"\x04type\x18\x05 \x01(\x0e2\x14.product.ProductTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12I\n" +
	"\x0fdigital_details\x18\b \x01(\v2\x1e.product.DigitalProductDetailsH\x00R\x0edigitalDetails\x12L\n" +
	"\x10physical_details\x18\t \x01(\v2\x1f.product.PhysicalProductDetailsH\x00R\x0fphysicalDetails\x12X\n" +
	"\x14subscription_details\x18\n" +
	" \x01(\v2#.product.SubscriptionProductDetailsH\x00R\x13subscriptionDetailsB\x11\n" +
	"\x0fproduct_details\"\x92\x03\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.product.ProductTypeR\x04type\x12I\n" +
	"\x0fdigital_details\x18\x05 \x01(\v2\x1e.product.DigitalProductDetailsH\x00R\x0edigitalDetails\x12L\n" +
	"\x10physical_details\x18\x06 \x01(\v2\x1f.product.PhysicalProductDetailsH\x00R\x0fphysicalDetails\x12X\n" +
	"\x14subscription_details\x18\a \x01(\v2#.product.SubscriptionProductDetailsH\x00R\x13subscriptionDetailsB\x11\n" +
	"\x0fproduct_details\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf8\x02\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12I\n" +
	"\x0fdigital_details\x18\x05 \x01(\v2\x1e.product.DigitalProductDetailsH\x00R\x0edigitalDetails\x12L\n" +
	"\x10physical_details\x18\x06 \x01(\v2\x1f.product.PhysicalProductDetailsH\x00R\x0fphysicalDetails\x12X\n" +
	"\x14subscription_details\x18\a \x01(\v2#.product.SubscriptionProductDetailsH\x00R\x13subscriptionDetailsB\x11\n" +
	"\x0fproduct_details\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"}\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x125\n" +
	"\vtype_filter\x18\x03 \x01(\x0e2\x14.product.ProductTypeR\n" +
	"typeFilter\"=\n" +
	"\x0fProductResponse\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.product.ProductR\aproduct\"\x96\x01\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize*X\n" +
	"\vProductType\x12\x1c\n" +
	"\x18PRODUCT_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\adigital\x10\x01\x12\f\n" +
	"\bphysical\x10\x02\x12\x10\n" +
	"\fsubscription\x10\x032\xfd\x02\n" +
	"\x0eProductService\x12H\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x18.product.ProductResponse\x12B\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x18.product.ProductResponse\x12H\n" +
	"\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x18.product.ProductResponse\x12F\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponseB\x15Z\x13grpc-product/pkg/pbb\x06proto3"

var (
	file_api_proto_product_proto_rawDescOnce sync.Once
	file_api_proto_product_proto_rawDescData []byte
)

func file_api_proto_product_proto_rawDescGZIP() []byte {
	file_api_proto_product_proto_rawDescOnce.Do(func() {
		file_api_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_product_proto_rawDesc), len(file_api_proto_product_proto_rawDesc)))
	})
	return file_api_proto_product_proto_rawDescData
}

var file_api_proto_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_product_proto_goTypes = []any{
	(ProductType)(0),                   // 0: product.ProductType
	(*DigitalProductDetails)(nil),      // 1: product.DigitalProductDetails
	(*PhysicalProductDetails)(nil),     // 2: product.PhysicalProductDetails
	(*SubscriptionProductDetails)(nil), // 3: product.SubscriptionProductDetails
	(*Product)(nil),                    // 4: product.Product
	(*CreateProductRequest)(nil),       // 5: product.CreateProductRequest
	(*GetProductRequest)(nil),          // 6: product.GetProductRequest
	(*UpdateProductRequest)(nil),       // 7: product.UpdateProductRequest
	(*DeleteProductRequest)(nil),       // 8: product.DeleteProductRequest
	(*ListProductsRequest)(nil),        // 9: product.ListProductsRequest
	(*ProductResponse)(nil),            // 10: product.ProductResponse
	(*ListProductsResponse)(nil),       // 11: product.ListProductsResponse
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 13: google.protobuf.Empty
}
var file_api_proto_product_proto_depIdxs = []int32{
	0,  // 0: product.Product.type:type_name -> product.ProductType
	12, // 1: product.Product.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: product.Product.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: product.Product.digital_details:type_name -> product.DigitalProductDetails
	2,  // 4: product.Product.physical_details:type_name -> product.PhysicalProductDetails
	3,  // 5: product.Product.subscription_details:type_name -> product.SubscriptionProductDetails
	0,  // 6: product.CreateProductRequest.type:type_name -> product.ProductType
	1,  // 7: product.CreateProductRequest.digital_details:type_name -> product.DigitalProductDetails
	2,  // 8: product.CreateProductRequest.physical_details:type_name -> product.PhysicalProductDetails
	3,  // 9: product.CreateProductRequest.subscription_details:type_name -> product.SubscriptionProductDetails
	1,  // 10: product.UpdateProductRequest.digital_details:type_name -> product.DigitalProductDetails
	2,  // 11: product.UpdateProductRequest.physical_details:type_name -> product.PhysicalProductDetails
	3,  // 12: product.UpdateProductRequest.subscription_details:type_name -> product.SubscriptionProductDetails
	0,  // 13: product.ListProductsRequest.type_filter:type_name -> product.ProductType
	4,  // 14: product.ProductResponse.product:type_name -> product.Product
	4,  // 15: product.ListProductsResponse.products:type_name -> product.Product
	5,  // 16: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	6,  // 17: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	7,  // 18: product.ProductService.UpdateProduct:input_type -> product.UpdateProductRequest
	8,  // 19: product.ProductService.DeleteProduct:input_type -> product.DeleteProductRequest
	9,  // 20: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	10, // 21: product.ProductService.CreateProduct:output_type -> product.ProductResponse
	10, // 22: product.ProductService.GetProduct:output_type -> product.ProductResponse
	10, // 23: product.ProductService.UpdateProduct:output_type -> product.ProductResponse
	13, // 24: product.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	11, // 25: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_product_proto_init() }
func file_api_proto_product_proto_init() {
	if File_api_proto_product_proto != nil {
		return
	}
	file_api_proto_product_proto_msgTypes[3].OneofWrappers = []any{
		(*Product_DigitalDetails)(nil),
		(*Product_PhysicalDetails)(nil),
		(*Product_SubscriptionDetails)(nil),
	}
	file_api_proto_product_proto_msgTypes[4].OneofWrappers = []any{
		(*CreateProductRequest_DigitalDetails)(nil),
		(*CreateProductRequest_PhysicalDetails)(nil),
		(*CreateProductRequest_SubscriptionDetails)(nil),
	}
	file_api_proto_product_proto_msgTypes[6].OneofWrappers = []any{
		(*UpdateProductRequest_DigitalDetails)(nil),
		(*UpdateProductRequest_PhysicalDetails)(nil),
		(*UpdateProductRequest_SubscriptionDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_product_proto_rawDesc), len(file_api_proto_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_product_proto_goTypes,
		DependencyIndexes: file_api_proto_product_proto_depIdxs,
		EnumInfos:         file_api_proto_product_proto_enumTypes,
		MessageInfos:      file_api_proto_product_proto_msgTypes,
	}.Build()
	File_api_proto_product_proto = out.File
	file_api_proto_product_proto_goTypes = nil
	file_api_proto_product_proto_depIdxs = nil
}
