// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/proto/subscription.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionPlanService_CreateSubscriptionPlan_FullMethodName      = "/subscription.SubscriptionPlanService/CreateSubscriptionPlan"
	SubscriptionPlanService_GetSubscriptionPlan_FullMethodName         = "/subscription.SubscriptionPlanService/GetSubscriptionPlan"
	SubscriptionPlanService_GetProductSubscriptionPlans_FullMethodName = "/subscription.SubscriptionPlanService/GetProductSubscriptionPlans"
	SubscriptionPlanService_UpdateSubscriptionPlan_FullMethodName      = "/subscription.SubscriptionPlanService/UpdateSubscriptionPlan"
	SubscriptionPlanService_DeleteSubscriptionPlan_FullMethodName      = "/subscription.SubscriptionPlanService/DeleteSubscriptionPlan"
)

// SubscriptionPlanServiceClient is the client API for SubscriptionPlanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Subscription Plan Service Definition
type SubscriptionPlanServiceClient interface {
	CreateSubscriptionPlan(ctx context.Context, in *CreateSubscriptionPlanRequest, opts ...grpc.CallOption) (*SubscriptionPlanResponse, error)
	GetSubscriptionPlan(ctx context.Context, in *GetSubscriptionPlanRequest, opts ...grpc.CallOption) (*SubscriptionPlanResponse, error)
	GetProductSubscriptionPlans(ctx context.Context, in *GetProductSubscriptionPlansRequest, opts ...grpc.CallOption) (*ListSubscriptionPlansResponse, error)
	UpdateSubscriptionPlan(ctx context.Context, in *UpdateSubscriptionPlanRequest, opts ...grpc.CallOption) (*SubscriptionPlanResponse, error)
	DeleteSubscriptionPlan(ctx context.Context, in *DeleteSubscriptionPlanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type subscriptionPlanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionPlanServiceClient(cc grpc.ClientConnInterface) SubscriptionPlanServiceClient {
	return &subscriptionPlanServiceClient{cc}
}

func (c *subscriptionPlanServiceClient) CreateSubscriptionPlan(ctx context.Context, in *CreateSubscriptionPlanRequest, opts ...grpc.CallOption) (*SubscriptionPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionPlanResponse)
	err := c.cc.Invoke(ctx, SubscriptionPlanService_CreateSubscriptionPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionPlanServiceClient) GetSubscriptionPlan(ctx context.Context, in *GetSubscriptionPlanRequest, opts ...grpc.CallOption) (*SubscriptionPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionPlanResponse)
	err := c.cc.Invoke(ctx, SubscriptionPlanService_GetSubscriptionPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionPlanServiceClient) GetProductSubscriptionPlans(ctx context.Context, in *GetProductSubscriptionPlansRequest, opts ...grpc.CallOption) (*ListSubscriptionPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubscriptionPlansResponse)
	err := c.cc.Invoke(ctx, SubscriptionPlanService_GetProductSubscriptionPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionPlanServiceClient) UpdateSubscriptionPlan(ctx context.Context, in *UpdateSubscriptionPlanRequest, opts ...grpc.CallOption) (*SubscriptionPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionPlanResponse)
	err := c.cc.Invoke(ctx, SubscriptionPlanService_UpdateSubscriptionPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionPlanServiceClient) DeleteSubscriptionPlan(ctx context.Context, in *DeleteSubscriptionPlanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SubscriptionPlanService_DeleteSubscriptionPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionPlanServiceServer is the server API for SubscriptionPlanService service.
// All implementations must embed UnimplementedSubscriptionPlanServiceServer
// for forward compatibility.
//
// Subscription Plan Service Definition
type SubscriptionPlanServiceServer interface {
	CreateSubscriptionPlan(context.Context, *CreateSubscriptionPlanRequest) (*SubscriptionPlanResponse, error)
	GetSubscriptionPlan(context.Context, *GetSubscriptionPlanRequest) (*SubscriptionPlanResponse, error)
	GetProductSubscriptionPlans(context.Context, *GetProductSubscriptionPlansRequest) (*ListSubscriptionPlansResponse, error)
	UpdateSubscriptionPlan(context.Context, *UpdateSubscriptionPlanRequest) (*SubscriptionPlanResponse, error)
	DeleteSubscriptionPlan(context.Context, *DeleteSubscriptionPlanRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSubscriptionPlanServiceServer()
}

// UnimplementedSubscriptionPlanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionPlanServiceServer struct{}

func (UnimplementedSubscriptionPlanServiceServer) CreateSubscriptionPlan(context.Context, *CreateSubscriptionPlanRequest) (*SubscriptionPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSubscriptionPlan not implemented")
}
func (UnimplementedSubscriptionPlanServiceServer) GetSubscriptionPlan(context.Context, *GetSubscriptionPlanRequest) (*SubscriptionPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptionPlan not implemented")
}
func (UnimplementedSubscriptionPlanServiceServer) GetProductSubscriptionPlans(context.Context, *GetProductSubscriptionPlansRequest) (*ListSubscriptionPlansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductSubscriptionPlans not implemented")
}
func (UnimplementedSubscriptionPlanServiceServer) UpdateSubscriptionPlan(context.Context, *UpdateSubscriptionPlanRequest) (*SubscriptionPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubscriptionPlan not implemented")
}
func (UnimplementedSubscriptionPlanServiceServer) DeleteSubscriptionPlan(context.Context, *DeleteSubscriptionPlanRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSubscriptionPlan not implemented")
}
func (UnimplementedSubscriptionPlanServiceServer) mustEmbedUnimplementedSubscriptionPlanServiceServer() {
}
func (UnimplementedSubscriptionPlanServiceServer) testEmbeddedByValue() {}

// UnsafeSubscriptionPlanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionPlanServiceServer will
// result in compilation errors.
type UnsafeSubscriptionPlanServiceServer interface {
	mustEmbedUnimplementedSubscriptionPlanServiceServer()
}

func RegisterSubscriptionPlanServiceServer(s grpc.ServiceRegistrar, srv SubscriptionPlanServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubscriptionPlanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionPlanService_ServiceDesc, srv)
}

func _SubscriptionPlanService_CreateSubscriptionPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionPlanServiceServer).CreateSubscriptionPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionPlanService_CreateSubscriptionPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionPlanServiceServer).CreateSubscriptionPlan(ctx, req.(*CreateSubscriptionPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionPlanService_GetSubscriptionPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionPlanServiceServer).GetSubscriptionPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionPlanService_GetSubscriptionPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionPlanServiceServer).GetSubscriptionPlan(ctx, req.(*GetSubscriptionPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionPlanService_GetProductSubscriptionPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductSubscriptionPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionPlanServiceServer).GetProductSubscriptionPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionPlanService_GetProductSubscriptionPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionPlanServiceServer).GetProductSubscriptionPlans(ctx, req.(*GetProductSubscriptionPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionPlanService_UpdateSubscriptionPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionPlanServiceServer).UpdateSubscriptionPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionPlanService_UpdateSubscriptionPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionPlanServiceServer).UpdateSubscriptionPlan(ctx, req.(*UpdateSubscriptionPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionPlanService_DeleteSubscriptionPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionPlanServiceServer).DeleteSubscriptionPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionPlanService_DeleteSubscriptionPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionPlanServiceServer).DeleteSubscriptionPlan(ctx, req.(*DeleteSubscriptionPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionPlanService_ServiceDesc is the grpc.ServiceDesc for SubscriptionPlanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionPlanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription.SubscriptionPlanService",
	HandlerType: (*SubscriptionPlanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubscriptionPlan",
			Handler:    _SubscriptionPlanService_CreateSubscriptionPlan_Handler,
		},
		{
			MethodName: "GetSubscriptionPlan",
			Handler:    _SubscriptionPlanService_GetSubscriptionPlan_Handler,
		},
		{
			MethodName: "GetProductSubscriptionPlans",
			Handler:    _SubscriptionPlanService_GetProductSubscriptionPlans_Handler,
		},
		{
			MethodName: "UpdateSubscriptionPlan",
			Handler:    _SubscriptionPlanService_UpdateSubscriptionPlan_Handler,
		},
		{
			MethodName: "DeleteSubscriptionPlan",
			Handler:    _SubscriptionPlanService_DeleteSubscriptionPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/subscription.proto",
}
