// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/subscription.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Subscription Plan Message
type SubscriptionPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,3,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // in days
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionPlan) Reset() {
	*x = SubscriptionPlan{}
	mi := &file_api_proto_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPlan) ProtoMessage() {}

func (x *SubscriptionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionPlan.ProtoReflect.Descriptor instead.
func (*SubscriptionPlan) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscriptionPlan) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SubscriptionPlan) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *SubscriptionPlan) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SubscriptionPlan) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SubscriptionPlan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SubscriptionPlan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Requests and Responses
type CreateSubscriptionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionPlanRequest) Reset() {
	*x = CreateSubscriptionPlanRequest{}
	mi := &file_api_proto_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionPlanRequest) ProtoMessage() {}

func (x *CreateSubscriptionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionPlanRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionPlanRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateSubscriptionPlanRequest) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *CreateSubscriptionPlanRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateSubscriptionPlanRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetSubscriptionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionPlanRequest) Reset() {
	*x = GetSubscriptionPlanRequest{}
	mi := &file_api_proto_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionPlanRequest) ProtoMessage() {}

func (x *GetSubscriptionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionPlanRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubscriptionPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductSubscriptionPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductSubscriptionPlansRequest) Reset() {
	*x = GetProductSubscriptionPlansRequest{}
	mi := &file_api_proto_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductSubscriptionPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductSubscriptionPlansRequest) ProtoMessage() {}

func (x *GetProductSubscriptionPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductSubscriptionPlansRequest.ProtoReflect.Descriptor instead.
func (*GetProductSubscriptionPlansRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductSubscriptionPlansRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type UpdateSubscriptionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionPlanRequest) Reset() {
	*x = UpdateSubscriptionPlanRequest{}
	mi := &file_api_proto_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionPlanRequest) ProtoMessage() {}

func (x *UpdateSubscriptionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionPlanRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSubscriptionPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSubscriptionPlanRequest) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *UpdateSubscriptionPlanRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdateSubscriptionPlanRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteSubscriptionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionPlanRequest) Reset() {
	*x = DeleteSubscriptionPlanRequest{}
	mi := &file_api_proto_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionPlanRequest) ProtoMessage() {}

func (x *DeleteSubscriptionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionPlanRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSubscriptionPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubscriptionPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *SubscriptionPlan      `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionPlanResponse) Reset() {
	*x = SubscriptionPlanResponse{}
	mi := &file_api_proto_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPlanResponse) ProtoMessage() {}

func (x *SubscriptionPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionPlanResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionPlanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptionPlanResponse) GetPlan() *SubscriptionPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type ListSubscriptionPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*SubscriptionPlan    `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionPlansResponse) Reset() {
	*x = ListSubscriptionPlansResponse{}
	mi := &file_api_proto_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionPlansResponse) ProtoMessage() {}

func (x *ListSubscriptionPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionPlansResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionPlansResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubscriptionPlansResponse) GetPlans() []*SubscriptionPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

var File_api_proto_subscription_proto protoreflect.FileDescriptor

const file_api_proto_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/subscription.proto\x12\fsubscription\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x86\x02\n" +
	"\x10SubscriptionPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1b\n" +
	"\tplan_name\x18\x03 \x01(\tR\bplanName\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8d\x01\n" +
	"\x1dCreateSubscriptionPlanRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\",\n" +
	"\x1aGetSubscriptionPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\"GetProductSubscriptionPlansRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"~\n" +
	"\x1dUpdateSubscriptionPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"/\n" +
	"\x1dDeleteSubscriptionPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x18SubscriptionPlanResponse\x122\n" +
	"\x04plan\x18\x01 \x01(\v2\x1e.subscription.SubscriptionPlanR\x04plan\"U\n" +
	"\x1dListSubscriptionPlansResponse\x124\n" +
	"\x05plans\x18\x01 \x03(\v2\x1e.subscription.SubscriptionPlanR\x05plans2\xbd\x04\n" +
	"\x17SubscriptionPlanService\x12m\n" +
	"\x16CreateSubscriptionPlan\x12+.subscription.CreateSubscriptionPlanRequest\x1a&.subscription.SubscriptionPlanResponse\x12g\n" +
	"\x13GetSubscriptionPlan\x12(.subscription.GetSubscriptionPlanRequest\x1a&.subscription.SubscriptionPlanResponse\x12|\n" +
	"\x1bGetProductSubscriptionPlans\x120.subscription.GetProductSubscriptionPlansRequest\x1a+.subscription.ListSubscriptionPlansResponse\x12m\n" +
	"\x16UpdateSubscriptionPlan\x12+.subscription.UpdateSubscriptionPlanRequest\x1a&.subscription.SubscriptionPlanResponse\x12]\n" +
	"\x16DeleteSubscriptionPlan\x12+.subscription.DeleteSubscriptionPlanRequest\x1a\x16.google.protobuf.EmptyB\x15Z\x13grpc-product/pkg/pbb\x06proto3"

var (
	file_api_proto_subscription_proto_rawDescOnce sync.Once
	file_api_proto_subscription_proto_rawDescData []byte
)

func file_api_proto_subscription_proto_rawDescGZIP() []byte {
	file_api_proto_subscription_proto_rawDescOnce.Do(func() {
		file_api_proto_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_subscription_proto_rawDesc), len(file_api_proto_subscription_proto_rawDesc)))
	})
	return file_api_proto_subscription_proto_rawDescData
}

var file_api_proto_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_subscription_proto_goTypes = []any{
	(*SubscriptionPlan)(nil),                   // 0: subscription.SubscriptionPlan
	(*CreateSubscriptionPlanRequest)(nil),      // 1: subscription.CreateSubscriptionPlanRequest
	(*GetSubscriptionPlanRequest)(nil),         // 2: subscription.GetSubscriptionPlanRequest
	(*GetProductSubscriptionPlansRequest)(nil), // 3: subscription.GetProductSubscriptionPlansRequest
	(*UpdateSubscriptionPlanRequest)(nil),      // 4: subscription.UpdateSubscriptionPlanRequest
	(*DeleteSubscriptionPlanRequest)(nil),      // 5: subscription.DeleteSubscriptionPlanRequest
	(*SubscriptionPlanResponse)(nil),           // 6: subscription.SubscriptionPlanResponse
	(*ListSubscriptionPlansResponse)(nil),      // 7: subscription.ListSubscriptionPlansResponse
	(*timestamppb.Timestamp)(nil),              // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                      // 9: google.protobuf.Empty
}
var file_api_proto_subscription_proto_depIdxs = []int32{
	8, // 0: subscription.SubscriptionPlan.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: subscription.SubscriptionPlan.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: subscription.SubscriptionPlanResponse.plan:type_name -> subscription.SubscriptionPlan
	0, // 3: subscription.ListSubscriptionPlansResponse.plans:type_name -> subscription.SubscriptionPlan
	1, // 4: subscription.SubscriptionPlanService.CreateSubscriptionPlan:input_type -> subscription.CreateSubscriptionPlanRequest
	2, // 5: subscription.SubscriptionPlanService.GetSubscriptionPlan:input_type -> subscription.GetSubscriptionPlanRequest
	3, // 6: subscription.SubscriptionPlanService.GetProductSubscriptionPlans:input_type -> subscription.GetProductSubscriptionPlansRequest
	4, // 7: subscription.SubscriptionPlanService.UpdateSubscriptionPlan:input_type -> subscription.UpdateSubscriptionPlanRequest
	5, // 8: subscription.SubscriptionPlanService.DeleteSubscriptionPlan:input_type -> subscription.DeleteSubscriptionPlanRequest
	6, // 9: subscription.SubscriptionPlanService.CreateSubscriptionPlan:output_type -> subscription.SubscriptionPlanResponse
	6, // 10: subscription.SubscriptionPlanService.GetSubscriptionPlan:output_type -> subscription.SubscriptionPlanResponse
	7, // 11: subscription.SubscriptionPlanService.GetProductSubscriptionPlans:output_type -> subscription.ListSubscriptionPlansResponse
	6, // 12: subscription.SubscriptionPlanService.UpdateSubscriptionPlan:output_type -> subscription.SubscriptionPlanResponse
	9, // 13: subscription.SubscriptionPlanService.DeleteSubscriptionPlan:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_subscription_proto_init() }
func file_api_proto_subscription_proto_init() {
	if File_api_proto_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_subscription_proto_rawDesc), len(file_api_proto_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_subscription_proto_goTypes,
		DependencyIndexes: file_api_proto_subscription_proto_depIdxs,
		MessageInfos:      file_api_proto_subscription_proto_msgTypes,
	}.Build()
	File_api_proto_subscription_proto = out.File
	file_api_proto_subscription_proto_goTypes = nil
	file_api_proto_subscription_proto_depIdxs = nil
}
